vich_uploader:
  db_driver: orm

  mappings:
    articles:
      uri_prefix: /articles/images
      upload_destination: '%kernel.project_dir%/public/articles/images'
      namer: Vich\UploaderBundle\Naming\UniqidNamer
